-- Insert sample data into the insights_data table
INSERT INTO insights_data (
    end_year, intensity, sector, topic, insight, url, region, start_year, 
    impact, added, published, country, relevance, pestle, source, title, likelihood
) VALUES 
('', 6, 'Energy', 'gas', 'Annual Energy Outlook', 'http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf', 'Northern America', '', '', 'January, 20 2017 03:51:25', 'January, 09 2017 00:00:00', 'United States of America', 2, 'Industries', 'EIA', 'U.S. natural gas consumption is expected to increase during much of the projection period.', 3),
('', 6, 'Energy', 'oil', 'Annual Energy Outlook', 'http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf', 'Northern America', '', '', 'January, 20 2017 03:51:24', 'January, 09 2017 00:00:00', 'United States of America', 2, 'Industries', 'EIA', 'Reference case U.S. crude oil production is projected to recover from recent declines.', 3),
('', 6, 'Energy', 'consumption', 'Annual Energy Outlook', 'http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf', 'Northern America', '', '', 'January, 20 2017 03:51:23', 'January, 09 2017 00:00:00', 'United States of America', 2, 'Industries', 'EIA', 'U.S. petroleum consumption is projected to remain below the 2005 level.', 3),
('', 6, 'Environment', 'oil', 'WRI Partnership Aims to Foster Supply Chain Transparency, Zero-Deforestation Strategies', 'http://www.sustainablebrands.com/news_and_views/supply_chain/sustainable_brands/wri_partnership_aims_foster_supply_chain_transparency', 'Central America', '', '', 'January, 20 2017 03:26:40', 'January, 18 2017 00:00:00', 'Mexico', 3, 'Environmental', 'sustainablebrands.com', 'Mars, Unilever, Cargill and Mondelēz are already using GFW Commodities to assess deforestation risks in their palm oil, soy and cocoa supply chains across a collective area of land the size of Mexico.', 2),
('2027', 60, 'Government', 'market', 'E-Boats, Anyone? Electric Boat Market To Reach $20 Billion By 2027, According To New Study', 'https://cleantechnica.com/2017/01/12/e-boats-anyone-electric-boat-market-reach-20b-2027-according-new-study/', '', '', '3', 'January, 18 2017 02:23:13', 'January, 13 2017 00:00:00', '', 5, 'Political', 'CleanTechnica', 'The market for non-military electric watercraft and marine motors will balloon to over $20 billion worldwide by 2027.', 4),
('2018', 16, 'Energy', 'oil', 'Oil prices will be much more volatile in 2017', 'http://www.news.tracanada.ca/2017/01/16/oil-prices-will-be-much-more-volatile-in-2017/', 'World', '2017', '', 'January, 17 2017 04:19:59', 'January, 16 2017 00:00:00', '', 4, 'Economic', 'TRAC News', 'Global oil prices will witness much more volatility in 2017 even though markets may rebalance in the first half of the year if output cuts pledged by producers are implemented.', 4),
('2018', 16, '', 'gdp', 'IMF affirms Nigeria''s recovery from recession, with 0.8% growth forecast', 'http://www.vanguardngr.com/2017/01/imf-affirms-nigerias-recovery-recession-0-8-growth-forecast/', 'Western Africa', '2017', '', 'January, 17 2017 03:25:45', 'January, 16 2017 00:00:00', 'Nigeria', 4, 'Economic', 'Vanguard News', 'Nigeria Gross Domestic Product will grow by 0.8 percent in 2017 and 2.3 percent in 2018.', 4),
('', 6, 'Aerospace & defence', 'war', 'Lebanon: No Land for Beginning Politicians', 'https://www.avimelamed.com/2017/01/07/lebanon-no-land-for-beginning-politicians/', 'Western Asia', '', '', 'January, 17 2017 03:18:22', 'January, 07 2017 00:00:00', 'Lebanon', 2, 'Political', 'Avi Melamed', 'A war in Lebanon will increase the already heavy economic burden Saudi Arabia is carrying.', 3),
('', 72, 'Information Technology', 'robot', '21 research reports forecast double-digit growth for robotics industry', 'https://www.therobotreport.com/news/21-research-reports-forecast-double-digit-growth-for-robotics-industry', 'World', '2022', '3', 'January, 14 2017 03:35:43', 'September, 01 2017 00:00:00', '', 6, 'Economic', 'therobotreport', 'Global logistics robots market is expected to grow to around $11.18 billion in 2022.', 4),
('2025', 9, 'Energy', 'battery', 'How Electric Trucks Will Shape The Auto Transport Industry', 'http://evobsession.com/electric-trucks-will-shape-auto-transport-industry/', '', '', '', 'January, 16 2017 05:54:47', 'January, 10 2017 00:00:00', '', 3, 'Technological', 'EV Obsession', 'Experts predict the costs of replacing electric batteries will decrease by 2.5x by 2025.', 3);
